spring:
  datasource:
    url: jdbc:mysql://123.124.209.84:3306/cronjob_engine?useUnicode=true&characterEncoding=utf-8
    username: poc1
    password: poc1@321
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    com.example.demo.dao : debug
